### ISSUE TITLE
How to decode?

### ISSUE THREAD

**Issue by ashwin8353** [htr-tech/PyObfuscate#2]
Cause I was encrypted an .py file. And deleted the normal file. Now I need that code. I can recover that with decoding. So can you upload the decode script.

**Comment by shhahid7** [comment]
I am also looking for decrypt.. i have encrypt the code but now i want to decrypt.. kindly share decrypt script.

**Comment by hngocuyen** [comment]
ez decrypt

**Comment by shhahid7** [comment]
Can you share that py script with me?

I will see and will revert back to you.

Thanks for responding my email.

**Comment by hngocuyen** [comment]
What kind of decrypt do you want?, I know decrypt mode 1-15, mode 16 very hard to reverse

**Comment by shhahid7** [comment]
Yes
Here is the file I am looking for decrypt

Pls find the attachment.

**Comment by shhahid7** [comment]
Well below is encryption type

It's

lambda __ :
__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]));exec((_)


I want to decrypt this..
Help ..

**Comment by shhahid7** [comment]
Well below is encryption type

It's

lambda __ :
__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]));exec((_)


If it is possible for u then pls share py script to decrypt this code.

**Comment by hngocuyen** [comment]
do you have telegram, i support you

**Comment by shhahid7** [comment]
Yes, find me on the tg my username is

@shhahid

**Comment by hngocuyen** [comment]
I can't find your name?, try to find my name 
@Tdatvuong
