### ISSUE TITLE
_ = lambda __: __import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))); ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by listmen001** [htr-tech/PyObfuscate#3]
Load obfuscate script and start at linux - nice work;
resend script user windows and this error born:

_ = lambda __: __import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(__[::-1])));
ValueError: bad marshal data (unknown type code)
How to solve it?

**Comment by htr-tech** [comment]
use the same python version used for encrypting

**Comment by listmen001** [comment]
> use the same python version used for encrypting

simple solve:
windows - didn't work;
linux - works;
choice: buy linux server :)
